### ISSUE TITLE
Compatibility with nextcloud 16

### ISSUE THREAD

**Issue by neddstark** [undo-ransomware/ransomware_detection#11]
This app is reported as incompatible with nextcloud 16.

**Comment by ilovemilk** [comment]
Thanks for the reminder! I will test it on the weekend and release a new version. 👍

**Comment by neddstark** [comment]
Awesome!

Thank you much for your time!

Best,
Florin

**Comment by ilovemilk** [comment]
Hi Florin

there is new version available in the app store! 😄 

Best regards
Matthias

**Comment by neddstark** [comment]
thank you much, Matthias!

Best,
Florin
