### ISSUE TITLE
Exhausted memory_limit

### ISSUE THREAD

**Issue by jonathanmmm** [undo-ransomware/ransomware_detection#12]
Hi,
3 days ago there was this error:
Allowed memory size of 536870912 bytes exhausted (tried to allocate 536870920 bytes) at /var/www/nextcloud/apps/ransomware_detection/lib/Analyzer/EntropyAnalyzer.php#141

I am using nextcloud 15.0.7
Php 7.3

I don't know what was uploaded, I believe an kali-linux.iso that I have.

**Comment by ilovemilk** [comment]
Hi jonathanmmm

thanks for reporting this bug! I found the bug. Hopefully I will have enough time at friday to release a bugfix.

Best regards
Matthias

**Comment by ilovemilk** [comment]
Hi jonathanmmm,

I published a new release to the appstore fixing this bug. Would be great if you could test if it works for you.

Best regards
Matthias

**Comment by jonathanmmm** [comment]
Have updated, I need to upload a big file or something, maybe tomorrow
