### ISSUE TITLE
All Files are suspicious

### ISSUE THREAD

**Issue by Happyfeet01** [undo-ransomware/ransomware_detection#13]
Hello,

i activate on my productive Nextcloud, this App.  I get many warnings, also a few of my Users.
<img width="940" alt="ramsomware" src="https://user-images.githubusercontent.com/3295104/57722679-46ae4780-7687-11e9-926f-7c785f709073.png">

What is wrong with the files? Only Folders are okay.

My system:
Ubuntu 18.04 LTS
Nginx

Nextcloud Version: 16.0.0.9

PHP:
Version: 7.3.5
Arbeitspeicher-Grenzwert: 1 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 2 GB

Mariadb 10.4.4

**Comment by ilovemilk** [comment]
Hi Happyfeet01

yellow means it is not critical only the red ones are. Maybe the naming of the levels are bit confusing. I recommend to set the notification level in the settings to "Very suspicious".

In our tests nearly all ransomware families were classified as "Very suspicious" (red) and only a few (about 10%) were classified as "Suspicious" (yellow).

We are currently working on a new version with a better classification based on machine learning and an improved interface. So if you have more feedback regarding UI we are more than happy if would notify us! :)

Best regards
Matthias
