### ISSUE TITLE
Error 500, conflicting calendar public share

### ISSUE THREAD

**Issue by arsasm** [undo-ransomware/ransomware_detection#15]
Nextcloud RAW log:

`{"reqId":"XPDtYwoAADIAAB9FGWoAAAAA","level":3,"time":"2019-05-31T09:01:23+00:00","remoteAddr":"STRIPPED","user":"--","app":"remote","method":"PROPFIND","url":"\/remote.php\/dav\/public-calendars\/Q2a35jrkZmDWSbEf","message":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"function":"beforeHttpPropFind","class":"OCA\\RansomwareDetection\\Connector\\Sabre\\RequestPlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.stripped.com\/remote.php\/dav\/public-calendars\/Q2a35jrkZmDWSbEf","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\RansomwareDetection\\Connector\\Sabre\\RequestPlugin"},"beforeHttpPropFind"],[{"absoluteUrl":"https:\/\/cloud.stripped.com\/remote.php\/dav\/public-calendars\/Q2a35jrkZmDWSbEf","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/cloud.stripped.com\/remote.php\/dav\/public-calendars\/Q2a35jrkZmDWSbEf","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.stripped.com\/remote.php\/dav\/public-calendars\/Q2a35jrkZmDWSbEf","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/remote.php","line":163,"args":["\/var\/www\/vhosts\/stripped.com\/content\/cloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/vhosts\/stripped.com\/content\/cloud\/apps\/ransomware_detection\/lib\/Connector\/Sabre\/RequestPlugin.php","Line":111,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/74.0.3729.169 Safari\/537.36","version":"16.0.1.1"}
`

**Comment by ilovemilk** [comment]
Hi arsasm
Thanks for reporting your issue,

I think I found the problem. I will try to release a problem as soon as possible.

Best regards
Matthias

**Comment by arsasm** [comment]
Hi ilovemilk, 

Okey, I think that the problem is trying to get user uid when no user is logged in. I haven't time to deep into the problem and help you more at the moment. But I can say that the calendar public link works on a browser with a session active.

Thanks and best regards. 
AR Sánchez.

**Comment by ilovemilk** [comment]
Hi Sánchez

That's the same I thought. Thus I will only analyze requests with a valid user session and will exclude the others. That shouldn't change anything for the ransomware detection part but should fix your problems! :)

Best regards
Matthias

**Comment by arsasm** [comment]
Hi Matthias,

Check also for the public uploads, maybe disable all public request analysis can be dangerous. But probably you have a way to disable requests from apps that doesn't need protection, like calendar or contacts.

Best regards.
AR Sánchez.

**Comment by ilovemilk** [comment]
Hi Sánchez,

the request plugin doesn't analyze files itself thus it doesn't lead to a security problem. It only builds the sync sequences. Thus ignoring these requests shouldn't change anything but should get rid of the error.

I already released a fix on Github but the Nextcloud appstore is buggy. I have to wait till it's fixed :(

Best regards
Matthias

**Comment by ilovemilk** [comment]
Hi
I was able to upload the release with the bugfix to the Nextcloud appstore. I would be happy if you could try it out! :)

Best regards
Matthias

**Comment by arsasm** [comment]
Hi

It's working fine!! 

Thanks and best regards.
AR Sánchez.
