### ISSUE TITLE
whitelist files

### ISSUE THREAD

**Issue by Happyfeet01** [undo-ransomware/ransomware_detection#16]
Hello, 

an User would upload some *.lock files zu his storage. But he can´t, Ramsomware detection means thats are bad files. He need the files for an Android Project.
Possible to whitelist some files?

**Comment by ilovemilk** [comment]
Hi Happyfeet01,

we will remove the file extension analysis in the new version thus we don't need the whitelisting anymore. 
Thanks for reporting the problem but I will close this for now.

Sincerely
Matthias

**Comment by Happyfeet01** [comment]
Thanks for your Information.
