### ISSUE TITLE
Ransomware Recovery affecting overall functionality

### ISSUE THREAD

**Issue by LtScoundrel** [undo-ransomware/ransomware_detection#17]
In addition to this Issue https://github.com/undo-ransomware/ransomware_detection/issues/6 

I ran into some memory problems as well. NextCloud 16.0.1, Ransomware Recovery 0.5.2 

The error message was: "{"reqId":"XSOq-VUNhRAAAGNSW9oAAAAQ","level":3,"time":"2019-07-08T20:43:53+00:00","remoteAddr":"xxxx","user":"--","app":"PHP","method":"PROPFIND","url":"/remote.php/webdav/xx/xx/xx/xx","message":"Allowed memory size of 402653184 bytes exhausted (tried to allocate 1179648 bytes) at /www/htdocs/yyyyy/xxxx.xxxx.xxxx/lib/private/AllConfig.php#418","userAgent":"--","version":"16.0.1.1","id":"5d23ab5f40c26"}

Line 418 of AllConfig.php contains the getUserValues - function which caches all information from the "preferences" table.

I had over 1.3 Million entries in this table. Only 39 were not from ransomware_detection 

ransomware_detection | propfind_count:046c6d04251bb26f9579b7917c546979 | 5|-- | -- | --

After deleting all those entries (did a copy of the table before) and deactivating the app. Everything is fine now.

**Comment by ilovemilk** [comment]
Hi LtScoundrel

Thanks for reporting the issue I will add a clean up mechanism to tackle this problem.
I will upload a new release with a bugfix in a few days.

Matthias

**Comment by Morganlej** [comment]
Trying to list the files i get no listing, just the spinning icon, same appearance as in issue #14 
https://user-images.githubusercontent.com/1286429/58323409-2a976c80-7e24-11e9-9a11-95d6a67afd1d.png

Memory exhausted here too; I see this in nextcloud log: 
"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /home/*obfuscated*/public_html/lib/public/AppFramework/Http/JSONResponse.php#71 "

Nextcloud 17.0.0.9, Ransomware Recovery 0.6.0
Hosted at https://owncube.com, no ssh access.

**Comment by ilovemilk** [comment]
Thanks that a very helpful hint. The app normally delivers all saved operations at once so if we the database has saved a large amount of operations that could be the problem.

It would be amazing if could execute the following command in you database
`SELECT COUNT(*) FROM oc_ransomware_detection` that we can check how much data the app collected to optimize the visualization with a pagination.

**Comment by Morganlej** [comment]
Glad to be of help. Sorry i have no access to database nor shell.  The most barebone i have is the occweb app.
@LtScoundrel ?

**Comment by ilovemilk** [comment]
Close due to complete rework of monitoring, analysis and UI.
