### ISSUE TITLE
"Detected suspicious file operations"

### ISSUE THREAD

**Issue by truelai** [undo-ransomware/ransomware_detection#21]
Nextcloud 16.0.1

I've received this notice but there is no link to any explanation. What should I be checking to see these operations? Shouldn't this have a link to the activity feed?

![detected](https://user-images.githubusercontent.com/4158476/65519711-66b30a80-deb4-11e9-8ff4-74beae98f7a0.png)

**Comment by ilovemilk** [comment]
Hi truelai,

Yes we are aware of the bad user interaction. We are already reworking the UI/UX to solve such problems.

For this version you have to check the application page there will be a list of file operations with the according classification.

Sincerely
Matthias

**Comment by truelai** [comment]
Ahhhh. Now I see. It's located at `/apps/ransomware_detection/`

Gotcha. Glad to hear you're improving UI/UX. Thanks for your work on this.
