### ISSUE TITLE
NC17 Notifier Ransomware recovery (id: ransomware_detection) is not considered because it is using the old way to register. at <<closure>>

### ISSUE THREAD

**Issue by JSoko** [undo-ransomware/ransomware_detection#22]
### Steps to reproduce
Activate Ransomware recovery
than the log is flooded with those errors

Could be this reason:
https://github.com/newroco/W2G2/issues/49
https://github.com/nextcloud/server/pull/15040

0. /var/www/nextcloud/apps/ransomware_detection/lib/AppInfo/Application.php line 186
   OC\Notification\Manager->registerNotifier(Closure {}, Closure {})
1. /var/www/nextcloud/apps/ransomware_detection/lib/AppInfo/Application.php line 140
   OCA\RansomwareDetection\AppInfo\Application->registerNotificationNotifier()
2. /var/www/nextcloud/apps/ransomware_detection/appinfo/app.php line 22
   OCA\RansomwareDetection\AppInfo\Application->register()
3. /var/www/nextcloud/lib/private/legacy/app.php line 260
   undefinedundefinedrequire_once("/var/www/nextcl ... p")
4. /var/www/nextcloud/lib/private/legacy/app.php line 154
   OC_App::requireAppFile(OCA\RansomwareDe ... {})
5. /var/www/nextcloud/lib/private/legacy/app.php line 127
   OC_App::loadApp("ransomware_detection")
6. /var/www/nextcloud/lib/base.php line 985
   OC_App::loadApps()
7. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /apps/logreader/poll?lastReqId=2mbmfw2m04N5TdRuQfIf
from 217.230.163.24 by ncadmin at 2019-09-26T17:47:45+02:00

### Expected behaviour
No errors in logfile

### Actual behaviour
{"reqId":"5rs09cRg8SY0BdllJc6F","level":3,"time":"2019-09-26T17:47:45+02:00","remoteAddr":"217.230.163.24","user":"ncadmin","app":"no app in context","method":"GET","url":"/apps/logreader/poll?lastReqId=2mbmfw2m04N5TdRuQfIf","message":{"Exception":"InvalidArgumentException","Message":"Notifier Ransomware recovery (id: ransomware_detection) is not considered because it is using the old way to register.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/ransomware_detection/lib/AppInfo/Application.php","line":186,"function":"registerNotifier","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"Closure"},{"__class__":"Closure"}]},{"file":"/var/www/nextcloud/apps/ransomware_detection/lib/AppInfo/Application.php","line":140,"function":"registerNotificationNotifier","class":"OCA\\RansomwareDetection\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/ransomware_detection/appinfo/app.php","line":22,"function":"register","class":"OCA\\RansomwareDetection\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":260,"args":["/var/www/nextcloud/apps/ransomware_detection/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":154,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\RansomwareDetection\\AppInfo\\Application"}]},{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":127,"function":"loadApp","class":"OC_App","type":"::","args":["ransomware_detection"]},{"file":"/var/www/nextcloud/lib/base.php","line":985,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Notification/Manager.php","Line":86,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36","version":"17.0.0.9","id":"5d8cdda15760d"}

## Server configuration detail

**Operating system:** Linux 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.16

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.7.1
 - audioplayer: 2.8.4
 - bookmarks: 2.1.1
 - calendar: 1.7.1
 - carnet: 0.18.0
 - cloud_federation_api: 1.0.0
 - cms_pico: 0.9.8
 - comments: 1.7.0
 - contacts: 3.1.3
 - data_request: 1.4.0
 - dav: 1.13.0
 - deck: 0.7.0
 - drop_account: 0.1.0
 - event_update_notification: 1.0.0
 - external: 3.4.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_downloadactivity: 1.6.0
 - files_fulltextsearch_tesseract: 1.3.1
 - files_linkeditor: 1.0.10
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.6.0
 - files_readmemd: 1.1.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trackdownloads: 1.6.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - gallery: 18.4.0
 - impersonate: 1.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - music: 0.10.1
 - news: 14.0.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.0.3
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - ocsms: 2.1.3
 - ownbackup: 19.9.0
 - password_policy: 1.7.0
 - piwik: 0.5.3
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - quickaccesssorting: 1.0.1
 - quota_warning: 1.6.0
 - recommendations: 0.5.0
 - richdocuments: 3.4.2
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.1
 - socialsharing_email: 1.0.5
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - telephoneprovider: 1.0.2
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - uploaddetails: 0.1.2
 - user_external: 0.7.0
 - user_usage_report: 1.1.2
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - files_external
 - firstrunwizard
 - ransomware_detection
 - spreed
 - suspicious_login
 - user_ldap
 - w2g2

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "loglevel": 2,
    "maintenance": false,
    "theme": "",
    "integrity.check.disabled": false,
    "overwrite.cli.url": "https:\/\/of99.net\/",
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "simpleSignUpLink.shown": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "log_rotate_size": "10485760",
    "activity_expire_days": 33,
    "trusted_domains": [
        "localhost",
        "192.168.1.234",
        "****.net",
        "office.****.net"
    ],
    "htaccess.RewriteBase": "\/",
    "trashbin_retention_obligation": "auto, 10",
    "versions_retention_obligation": "auto, 21",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "preview_max_x": 500,
    "preview_max_y": 500,
    "preview_max_scale_factor": 10,
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "tasks",
        "w2g2",
        "apporder",
        "piwik",
        "ownbackup",
        "radio",
        "carnet",
        "theming",
        "workin2gether",
        "files_linkeditor",
        "socialsharing_email",
        "files_readmemd",
        "spreed",
        "telephoneprovider",
        "drop_account",
        "issuetemplate",
        "polls",
        "ocsms",
        "quickaccesssorting",
        "cms_pico",
        "ransomware_detection"
    ],
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by ilovemilk** [comment]
Thanks for reporting this problem we have this already in issue #18 so I will close this here.

I will fix this with version 0.6.0.
