### ISSUE TITLE
Nextcloud server 18 shows incompatibility warning

### ISSUE THREAD

**Issue by torstendoerschel** [undo-ransomware/ransomware_detection#27]
To Reproduce

    Install Ransomware recovery 0.6.0
    Upgrade server to 18
    Ransomware recovery automatically gets disabled + shows warning + no available update

Expected behavior
Update app to show which lists nextcloud 18 as compatible in info.xml

Actual behavior
Nextcloud server 18 shows incompatibility warning

Server configuration
Nextcloud version: 18.0.0 RC2
Ransomware recovery version: 0.6.0

Updated from an older Nextcloud or fresh install: update from nextcloud 17

**Comment by neddstark** [comment]
Any progress for this one? Nextcloud already released v18 but upgrade it's not possible because of this.

**Comment by SimJoSt** [comment]
@ilovemilk will you be able to work on this?  
Does anything need to be change or is it enough to just raise the version number in the compatibility info?

**Comment by ilovemilk** [comment]
I will make some time to work on this app this week. I will evaluate the compatibility and release a new version!

**Comment by ilovemilk** [comment]
I released a new version 0.7.0 with Nextcloud 18 compatibility to the Nextcloud app store.

Thanks for the patience! 😄

**Comment by magikmw** [comment]
0.7.0 still reports as incompatible for some reason on 18.0.3

**Comment by SimJoSt** [comment]
@ilovemilk great! Unfortunately the changelog says again:
> Nextcloud version 17 support.

;-)

**Comment by ilovemilk** [comment]
Stupid me, failed the copy & paste! :) I fix this with 0.7.1 💥
