### ISSUE TITLE
Compatibility with nextcloud 18

### ISSUE THREAD

**Issue by neddstark** [undo-ransomware/ransomware_detection#28]
This app is reported as incompatible with nextcloud 18.

**Comment by Zocker1999NET** [comment]
Duplicate of #27 I think

**Comment by neddstark** [comment]
indeed it's duplicate of #27 but I was hoping for more visibility for the maintainer, to speed up releasing this for nextcloud 18

**Comment by SimJoSt** [comment]
That's a nice idea, but I don't think it is helpful :)  
One issue should suffice and is better for not cluttering the repo ;)

**Comment by ilovemilk** [comment]
I will make some time to work on this app this week. I will evaluate the compatibility and release a new version! I will get back to you in #27.
