### ISSUE TITLE
SSL error during download

### ISSUE THREAD

**Issue by FvdLaar** [undo-ransomware/ransomware_detection#31]
when downloading and enabling this nextcloud app i get : "cURL error 60: SSL certificate problem: certificate has expired (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**Comment by cromefire** [comment]
The certificate of the domain `wusa.io` is expired

**Comment by FvdLaar** [comment]
How is "wusa.io" used and is there an alternative?

**Comment by cromefire** [comment]
I don't know, I can provide some details from my sentry issue

**Comment by cromefire** [comment]
![image](https://user-images.githubusercontent.com/26320625/82753802-d7565200-9dc8-11ea-9532-80b81942f72d.png)

**Comment by FvdLaar** [comment]
Well then the workaround is:
- downloading the tar file using a workstation with browser AND accepting an invalid SLL certificate 
- transferring the tar manually to the nextcloud server
- unpack the tar file in the APPS dir

Hopefully the Let's Encrypt SSL certificate will be renewed soon by the Site "owner". It is just bad site management.

**Comment by ilovemilk** [comment]
Hi, 
sorry for the inconvenience the lets encrypt cronjob wasn't running anymore I triggered a refresh and now everything should work again.

**Comment by FvdLaar** [comment]
Well done! Case closed :-)
