### ISSUE TITLE
"Backends provided no user object for" errors

### ISSUE THREAD

**Issue by SimJoSt** [undo-ransomware/ransomware_detection#32]
When having the ransomware app enabled a lot of "Backends provided no user object for" errors appear in the log. A similar error has already been documented in https://github.com/nextcloud/server/issues/3302 and solved in https://github.com/nextcloud/files_downloadactivity/pull/8. I believe this is something similar.  
Some of the errors stem from using this app in tandem with the richdocuments app connected to a Collabora instance.

If this is in fact not fixable in this app, please refer me to the correct repository :)

**Comment by ilovemilk** [comment]
Can you post the logs with the error? That could help alot!

**Comment by ilovemilk** [comment]
Closed due to inactivity.

**Comment by SimJoSt** [comment]
@ilovemilk I checked if the error is still occurring, but couldn't find any current ones.  
If these messages do appear again, I will update the issue.
