### ISSUE TITLE
Compatibility with Nextcloud 20

### ISSUE THREAD

**Issue by plinss** [undo-ransomware/ransomware_detection#38]
The app is reporting incompatible with Nextcloud 20

**Comment by neddstark** [comment]
The core is already to 20.0.2
Should we expect a new release of this awesome module anytime soon? :)

**Comment by kosli** [comment]
@ilovemilk  any update regards NC 20.0.2 compatibility?

**Comment by kosli** [comment]
@ilovemilk I just saw all your commits/work in the rework-ui branch. Great. Looking forward to a new versoin :+1:

**Comment by ilovemilk** [comment]
Hey guys,

sorry for the late response! I just released a new version 0.9.0 with the Nextcloud 20 compatibility.

Matthias

**Comment by nolens** [comment]
@ilovemilk 

It just seems that version 0.9.0 does not show up in NC 20 .... And also not on the App Store page. Can you please look into this again?

Thomas

**Comment by ilovemilk** [comment]
Hi Thomas,
because of #48 I removed the app version 0.9.0 from the Appstore. I will release a fixed version soon together with the NC 20 comaptibility.

Matthias
